#!/usr/bin/perl

use IO::Socket; 
my $sock = new IO::Socket::INET ( 
PeerAddr => 'poirot', 
PeerPort => '42126', 
Proto => 'tcp', 
); 
die "Could not create socket: $!\n" unless $sock; 
print $sock "Hello there!\n"; 
close($sock);

