#!/home/oracle/perl/bin/perl
    eval 'exec /opt/share/oracle/bin/perl -S $0 ${1+"$@"}'
	if $running_under_some_shell;

require "find.pl";

# Traverse desired filesystems

&find('/home/jkstill');

exit;

sub wanted {

	print "$dir/$_\n";
	 return undef unless -d "$dir/$_";
	 $dir =~ /.*\/sccs$/ && do {
	 	chdir("$dir");
		chomp ($cwd=`pwd`);
		print "CWD: $cwd \n";
	 };
}

