#!/usr/bin/perl

# make sure that the grp_dept number is correct for this group

open(NWL,"fold -94 $ARGV[0]|") || die "could not open $ARGV[0]\n";
$GrpDept="  5400";
$Interval = 50;
$Counter = 0;

#while (read(NWL,$_,94) > 0 ) {
while (<NWL>) {

	$ElgRec = $_;
	$RecCode = substr($ElgRec,0,1);

	if( $RecCode == 2 ) { # detail record
		#substr($ElgRec,57,8) = $BirthDate;
		substr($ElgRec,66,6) = $GrpDept;
	}
		
	print STDOUT $ElgRec;

	$Counter++;
	if( $Counter >= $Interval ) {
		$Counter = 0;
		#print STDERR ".";
	}

}
