#!/usr/bin/env perl

my $x = dec2bin(-1004142592);
print "$x\n";

my $x = bin2dec(11000100001001100000000000000000);

sub dec2bin {
	my $str = unpack("B32", pack("N", shift));
	$str =~ s/^0+(?=\d)//;   # otherwise you'll get leading zeros
	return $str;
}


sub bin2dec {
	return unpack("N", pack("B32", substr("0" x 32 . shift, -32)));
}


