#!/home/oracle/perl/bin/perl

# test/demo retreiving a password

use OraEnv;
use strict;
no strict 'vars';

use Getopt::Long;

my($result) = Getopt::Long::GetOptions("database:s","username:s","z","h","help");

# tell -w to shut up
$opt_z = $opt_z;
$opt_help=$opt_help;
$opt_h=$opt_h;

#setup environment - homegrown package

my($db, $username, $password);

if ( ! defined($opt_database) ) {
	Usage();
	die "database required\n";
}

$db=$opt_database;
OraEnv::SetEnv($db);
if ( ! defined($opt_username) ) {
	Usage();
	die "username required\n";
}

$username=$opt_username;
$password = OraEnv::GetPassWord($db,$username);

print "USERNAME: $username\n";
print "DATABASE: $db\n";
print "PASSWORD: $password\n";


sub Usage {
	print "usage: OraEnv_password_test\n";
	print "\n";
	print "   OraEnv_password_test -database [database] -username [username]\n\n";
}

