#!/usr/bin/perl

while (<>) {
	s/,+/_/g;
	my $result = (eval $_);

	if ($@) {
		print qq{

You seem to have encountered an error
err: $@

Use CTL-C to exit

};
	}

	print commify($result) . "\n";

}

sub commify {
	# wn - working number
	my $wn = shift;
	unless ( $wn =~ /^\-{0,1}[0-9]+\.{0,1}[0-9]*$/ ) { return $wn; }
	1 while $wn =~ s/^(-?\d+)(\d{3})/$1,$2/;
	return $wn;
}

