#!/home/oracle/perl/bin/perl 

=head1

  show all available fields for Proc::ProcessTable

=cut 

# Dump all the available fields
use Proc::ProcessTable;

$t = new Proc::ProcessTable;

foreach my $field (sort $t->fields) {
	print $field, "\n";
}


